version: "3.8"
services:
    php:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        environment:
        - API_BASE_URL=http://www.omdbapi.com
        - API_KEY=replaceme
networks:
    php:
        driver: bridge
